
"""UAS-ML-NIAMILAH NABIL SYAHPUTRA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RpGu1mxKZ6HeUj1UQpPSugmDzKvuTV0C
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay


from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

df = pd.read_csv('/content/Data minyak atsiri.xlsx - Lembar1.csv')

"""# Import Data"""

df.head()

"""# Preprocessing Data"""

df.isnull().sum()

df.columns

# Kolom sensor
sensor_cols = ['Sensor1', 'Sensor2', 'Sensor3',
       'Sensor4']

# Ganti koma menjadi titik dan ubah ke float
for col in sensor_cols:
    df[col] = df[col].astype(str).str.replace(',', '.').astype(float)

X = df[['Sensor1', 'Sensor2', 'Sensor3',
       'Sensor4']]
y = df['Jenis sampel']

# Encoding Label
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

print("Mapping Label:")
for i, label in enumerate(encoder.classes_):
    print(f"{label} -> {i}")

# normalisasi data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""# Spliting data"""

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_encoded,
    test_size=0.3,
    random_state=42,
    stratify=y_encoded
)

"""# Algoritma KNN"""

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)

cm_knn = confusion_matrix(y_test, y_pred_knn)

print("Confusion Matrix KNN:\n", cm_knn)
print("Akurasi:", accuracy_score(y_test, y_pred_knn))
print("Presisi:", precision_score(y_test, y_pred_knn, average='macro'))
print("Recall:", recall_score(y_test, y_pred_knn, average='macro'))
print("F1-Score:", f1_score(y_test, y_pred_knn, average='macro'))

"""# Aloritma SVM"""

svm = SVC(kernel='rbf')
svm.fit(X_train, y_train)

y_pred_svm = svm.predict(X_test)

cm_svm = confusion_matrix(y_test, y_pred_svm)

print("Confusion Matrix SVM:\n", cm_svm)
print("Akurasi:", accuracy_score(y_test, y_pred_svm))
print("Presisi:", precision_score(y_test, y_pred_svm, average='macro'))
print("Recall:", recall_score(y_test, y_pred_svm, average='macro'))
print("F1-Score:", f1_score(y_test, y_pred_svm, average='macro'))

"""# Algoritma Naive Bayes"""

nb = GaussianNB()
nb.fit(X_train, y_train)

y_pred_nb = nb.predict(X_test)

cm_nb = confusion_matrix(y_test, y_pred_nb)

print("Confusion Matrix Naive Bayes:\n", cm_nb)
print("Akurasi:", accuracy_score(y_test, y_pred_nb))
print("Presisi:", precision_score(y_test, y_pred_nb, average='macro'))
print("Recall:", recall_score(y_test, y_pred_nb, average='macro'))
print("F1-Score:", f1_score(y_test, y_pred_nb, average='macro'))

# evaluasi
from sklearn.metrics import classification_report

print("=== KNN ===")
print(classification_report(y_test, y_pred_knn))

print("=== SVM ===")
print(classification_report(y_test, y_pred_nb))

print("=== Naive Bayes ===")
print(classification_report(y_test, y_pred_nb))



"""# PCA Visualisasi"""

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

plt.figure(figsize=(8,6))

for label in np.unique(y_encoded):
    plt.scatter(
        X_pca[y_encoded == label, 0],
        X_pca[y_encoded == label, 1],
        label=encoder.inverse_transform([label])[0]
    )

plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.title("Visualisasi PCA Data Minyak Atsiri")
plt.legend()
plt.grid(True)
plt.show()

"""# CEK 1 — TRAIN vs TEST ACCURACY"""

# Prediksi data latih
y_train_pred = nb.predict(X_train)
y_test_pred  = nb.predict(X_test)

# Akurasi
train_acc = accuracy_score(y_train, y_train_pred)
test_acc  = accuracy_score(y_test, y_test_pred)

print(f"Akurasi Training : {train_acc:.4f}")
print(f"Akurasi Testing  : {test_acc:.4f}")
print(f"Selisih          : {abs(train_acc - test_acc):.4f}")

"""# CEK 2 — CROSS VALIDATION"""

from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
    nb, X_scaled, y_encoded,
    cv=5,
    scoring='accuracy'
)

print("Akurasi tiap fold :", cv_scores)
print("Rata-rata akurasi :", cv_scores.mean())
print("Standar deviasi  :", cv_scores.std())

"""# CEK 3 — LEARNING CURVE"""

from sklearn.model_selection import learning_curve

train_sizes, train_scores, test_scores = learning_curve(
    nb,
    X_scaled,
    y_encoded,
    cv=5,
    scoring='accuracy',
    train_sizes=np.linspace(0.1, 1.0, 10)
)

train_mean = train_scores.mean(axis=1)
test_mean  = test_scores.mean(axis=1)

plt.figure(figsize=(8,5))
plt.plot(train_sizes, train_mean, label='Training Accuracy')
plt.plot(train_sizes, test_mean, label='Testing Accuracy')
plt.xlabel("Jumlah Data Training")
plt.ylabel("Accuracy")
plt.title("Learning Curve - Naive Bayes")
plt.legend()
plt.grid(True)
plt.show()



"""# Confusion Matriks KNN"""

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_knn)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Kunyit Putih', 'Temulawak', 'Temuireng'],
            yticklabels=['Kunyit Putih', 'Temulawak', 'Temuireng'])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix KNN")
plt.show()

"""# Confusion Matriks SVM"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

labels = ['Kunyit Putih', 'Temulawak', 'Temuireng']

cm_svm = confusion_matrix(y_test, y_pred_svm)

disp_svm = ConfusionMatrixDisplay(confusion_matrix=cm_svm,
                                  display_labels=labels)
disp_svm.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix SVM")
plt.show()

"""# Confusion Matrik Naive Bayes"""

cm_nb = confusion_matrix(y_test, y_pred_nb)

disp_nb = ConfusionMatrixDisplay(confusion_matrix=cm_nb,
                                 display_labels=labels)
disp_nb.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix Naive Bayes")
plt.show()